application: udacity-wiki-timur
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: /.*
  script: udacity-wiki-timur.app


libraries:
- name: jinja2                                                                  
  version: latest   

builtins:
- remote_api: on
